---
title: "2018-10-06_network_analysis"
author: "YT"
date: "6 October 2018"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import library and data

```{r}
library(tidyverse);
setwd("D:/R/20181006");
publications <- read_csv("pubmed_result2.csv") %>% data.frame();
```

## Define nodes, and rank authors by number of publications
```{r}
# Remove et al. from the author list and split the individual names
authors <- gsub(",et al.", "", publications$Description)
authors <- gsub(", et al.", "", authors) 
authors <- gsub("Jäger", "Jaeger", authors) 
authors <- gsub("[.]","",authors) %>% 
  strsplit(", ")

# author_list contains the individual author names, without co-authorship information
author_list <- unlist(authors) %>% 
  data.frame() 
names(author_list) <- "label"

nodes <- distinct(author_list, label)

names(nodes) <- "label"
nodes <- nodes %>% rowid_to_column("id")


paper_per_author <- author_list %>%
  group_by(label) %>%
  summarise(count = n())

paper_per_author$ID <- paper_per_author$label

arrange(paper_per_author, desc(count)) %>%
  write.csv(file="author_rankings.csv",sep=",",na="NA",row.names=FALSE, col.names = TRUE)

nodes2 <- paper_per_author %>% rowid_to_column("id")

```

## Define edges
```{r}
authors <- lapply(authors, sort)

edges <- tribble(~Source, ~Target, ~Type, ~Weight)

for (i in 1:length(authors)){
  #print(i)
  if (length(authors[[i]])<2){
    #print("skip")
    next
  }
 
  for (j in 1:(length(authors[[i]])-1)){
    #print("A")
    #print(j)
    for (k in (j+1):length(authors[[i]])){
      # SOME MESSY WORK IN PROGRESS!!!
      #print("B")
      #print(k)
      if (nrow(filter(edges, Source==authors[[i]][j], Target==authors[[i]][k]))!=0) #if there are more than one row, we are in trouble
        {
        #print("match fountd")
        #print(filter(edges, A==authors[[i]][j], B==authors[[i]][k]))
        
        edges <- mutate(edges, Weight = ifelse(Source==authors[[i]][j] & Target==authors[[i]][k], Weight+1, Weight)) 
        
        #print(authors[[i]][j])
        #print(authors[[i]][k])
        } 
      else {
        edges <- add_row(edges, Source=authors[[i]][j], Target=authors[[i]][k],Type = "Undirected", Weight=1);
      }
    }
  }
  
}

arrange(edges, desc(Weight)) %>%
  write.csv(file="edges.csv",sep=",",na="NA",row.names=FALSE, col.names = TRUE)

```


## Visualize network using "network" package

```{r}
edges_name <- c(edges$A, edges$B) %>% tibble() %>% distinct()
names(edges_name) <- "label"

idx <- which(nodes2$label %in% edges_name$label == 0);
nodes3 <-nodes2[-idx, ];
  
library(network)
routes_network <- network(edges, directed = FALSE, matrix.type = "edgelist", ignore.eval = FALSE)
routes_network %v%"id" <- nodes2$id
routes_network %v%"count" <- nodes2$count
plot(routes_network, vertex.cex = 3, mode = "circle")


```


## "igraph" package

```{r}
detach(package:network)
rm(routes_network)
library(igraph)

routes_igraph <- graph_from_data_frame(d = edges, directed = FALSE)
plot(routes_igraph, edge.arrow.size = 0.2)
plot(routes_igraph, layout = layout_with_graphopt, vertex.shape = "none", vertex.label = NA)


```

